# Generated by Django 4.2.26 on 2025-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('ml', 'Machine Learning / AI'), ('desktop', 'Desktop Application'), ('mobile', 'Mobile App'), ('iot', 'IoT / Hardware'), ('other', 'Other')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4, help_text='Approx. time to complete (in weeks)'),
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
